#!/bin/bash

ZIP="youpay-woocommerce.zip"
TARGETDIR='deploy'

######## Setup Functions #############
# prints colored text
print_style () {

    if [ "$2" == "info" ] ; then
        COLOR="96m";
    elif [ "$2" == "success" ] ; then
        COLOR="92m";
    elif [ "$2" == "warning" ] ; then
        COLOR="93m";
    elif [ "$2" == "danger" ] ; then
        COLOR="91m";
    else #default color
        COLOR="0m";
    fi

    STARTCOLOR="\e[$COLOR";
    ENDCOLOR="\e[0m";

    printf "$STARTCOLOR%b$ENDCOLOR" "$1";
}

################################################

echo "Hello friend..."
printf "\n\n"
print_style "===== YouPay WooCommerce Build and Release =====\n" "danger";
echo "this will build and release this package for you"
print_style "TODO: finish\n" "info"
printf "\n"
################################################

print_style "Preping...." "info"
rm -rf ${TARGETDIR}
printf "."
mkdir "${TARGETDIR}"
printf ".\n"

print_style "Copying all files" "info"
for file in *
do
  if [ "$file" != "$TARGETDIR" ] && [ "$file" != "vendor" ] && [ "$file" != "build" ] && [ "$file" != "$ZIP" ]
  then
    cp -r "$file" "$TARGETDIR/";
    print_style "." "success"
  fi
done
print_style "✓" "success"
printf "\n"

cd $TARGETDIR || ( print_style "Changing Directory Failed" "error" && exit );

print_style "Installing Composer...\n" "info"

composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --no-suggest --optimize-autoloader --classmap-authoritative &>/dev/null

print_style "Composer Installed\n" "success"
cd ../

print_style "Zipping\n" "info"
zip -r $ZIP $TARGETDIR &>/dev/null
print_style "File Packaged Up Successfully\n" "success"

print_style "...cleaning up" "info"
rm -rf ${TARGETDIR}

print_style "\n\nBuild Completed:\n" "success"
print_style "./${ZIP}\n\n" "info"

print_style "TODO: Release auto to github and Wordpress.org" "danger"
echo ""
exit;
while true; do
    read -p "Do you wish to release this package?" yn
    case $yn in
        [Yy]* ) echo "DONE"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done